//* September 24: Find the Difference

// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
// Bit manipulation - same as 'find unique number in array of pairs' - use XOR
// a ^ a = 0
// a ^ b ^ a ^ b = a ^ a ^ b ^ b = 0 ^ 0 = 0
// a ^ b ^ c ^ a ^ b = 0 ^ c = c
// Time: O(n), Space: O(1)
    let diff = 0;
    for (let i = 0; i < s.length; i++) {
        diff ^= s.charCodeAt(i);
    }
    for (let i = 0; i < t.length; i++) {
        diff ^= t.charCodeAt(i);
    }
    return String.fromCharCode(diff);
    
// Brute force
// Time: O(n), Space: O(n)
    // const freqs = {};
    // for (let i = 0; i < s.length; i++) {
    //     freqs[s[i]] = freqs[s[i]] + 1 || 1;
    // }
    // for (let i = 0; i < t.length; i++) {
    //     if (freqs[t[i]] > 0) freqs[t[i]] -= 1;
    //     else return t[i];
    // }
    // return -1;  // should never happen if parameter strings are valid
};